# Generated by Django 5.0.1 on 2025-08-19 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('keras_h5', 'Keras H5'), ('tensorflow_saved_model', 'TensorFlow SavedModel'), ('pytorch', 'PyTorch'), ('onnx', 'ONNX')], max_length=50)),
                ('model_path', models.CharField(max_length=500)),
                ('input_shape', models.JSONField(help_text='Input shape as JSON array, e.g., [225, 5]')),
                ('num_categories', models.IntegerField()),
                ('confidence_threshold', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_loaded', models.BooleanField(default=False)),
                ('categories', models.JSONField(help_text='List of category names')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
