# Generated by Django 5.0.1 on 2025-10-08 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_classifications', models.IntegerField(default=0)),
                ('high_confidence_count', models.IntegerField(default=0)),
                ('low_confidence_count', models.IntegerField(default=0)),
                ('multiple_candidates_count', models.IntegerField(default=0)),
                ('uncertain_count', models.IntegerField(default=0)),
                ('dns_detections', models.IntegerField(default=0)),
                ('asn_fallback_count', models.IntegerField(default=0)),
                ('avg_prediction_time_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_stats', to='classifier.modelconfiguration')),
            ],
            options={
                'verbose_name_plural': 'Classification Statistics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_configuration', '-timestamp'], name='classifier__model_c_11b4ee_idx'), models.Index(fields=['-timestamp'], name='classifier__timesta_844218_idx')],
            },
        ),
    ]
