# Generated by Django 5.0.1 on 2025-11-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_classificationstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationstats',
            name='vpn_detections',
            field=models.IntegerField(default=0),
        ),
    ]
