---
- name: Test if remote connection and SUDO privileges work
  hosts: localserver
  gather_facts: yes
  become: true
  vars_files:
    - config.yml
  tasks:
    - name: Add ports to OVS bridge
      command: "ovs-vsctl add-port {{ bridge_name }} {{ item }}"
      with_items: "{{ interfaces }}"
      when:
        - item != 'lo'