# Generated by Django 5.0.1 on 2024-01-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('switch', 'Switch'), ('access_point', 'Access Point'), ('server', 'Server')], max_length=20)),
                ('os_type', models.CharField(choices=[('ubuntu_20_server', 'Ubuntu 20 Server'), ('ubuntu_22_server', 'Ubuntu 22 Server')], max_length=20)),
                ('lan_ip_address', models.GenericIPAddressField(unique=True)),
                ('ports', models.IntegerField(null=True)),
                ('ovs_enabled', models.BooleanField(default=False)),
                ('ovs_version', models.CharField(max_length=10, null=True)),
                ('openflow_version', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
