# Generated by Django 5.0.1 on 2024-01-15 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_device_ports_bridge_port'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='ports',
            new_name='num_ports',
        ),
        migrations.AddField(
            model_name='port',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='general.device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='port',
            name='bridge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='general.bridge'),
        ),
    ]
