# Generated by Django 5.0.1 on 2024-01-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_rename_ports_device_num_ports_port_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(default='M@ster789@', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='username',
            field=models.CharField(default='keegan', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
