# Generated by Django 5.0.1 on 2024-02-02 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_device_password_device_username_alter_port_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ports', to='general.bridge'),
        ),
    ]
