# Generated by Django 5.0.1 on 2024-02-07 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_device_os_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('onos', 'Onos'), ('odl', 'Open Daylight'), ('other', 'Other')], max_length=20)),
                ('lan_ip_address', models.GenericIPAddressField(unique=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller', to='general.device')),
                ('switches', models.ManyToManyField(related_name='switch_controllers', to='general.device')),
            ],
        ),
        migrations.AddField(
            model_name='bridge',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bridges', to='general.controller'),
        ),
    ]
