# Generated by Django 5.0.1 on 2024-02-07 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_controller_bridge_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdn_controller', to='general.device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='openflow_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ovs_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
