# Generated by Django 5.0.1 on 2024-02-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_controller_port_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
