# Generated by Django 5.0.1 on 2024-03-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_alter_port_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='type',
            field=models.CharField(choices=[('onos', 'Onos'), ('odl', 'Open Daylight'), ('faucet', 'Faucet'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('switch', 'Switch'), ('access_point', 'Access Point'), ('server', 'Server'), ('controller', 'Controller'), ('vm', 'Virtual Machine')], max_length=20),
        ),
    ]
