# Generated by Django 5.0.1 on 2024-03-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_alter_controller_type_alter_device_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='lan_ip_address',
        ),
    ]
