# Generated by Django 5.0.1 on 2024-06-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_alter_port_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number_of_bytes', models.IntegerField()),
                ('number_of_packets', models.IntegerField()),
                ('categories', models.CharField(max_length=200)),
            ],
        ),
    ]
