# Generated by Django 5.0.1 on 2024-06-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_classifiermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiermodel',
            name='categories',
            field=models.CharField(max_length=1000),
        ),
    ]
