# Generated by Django 5.0.1 on 2024-06-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_alter_classifiermodel_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=200)),
                ('long_description', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('installed', models.BooleanField(default=False)),
            ],
        ),
    ]
