# Generated by Django 5.0.1 on 2024-06-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_plugins'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugins',
            name='switches',
            field=models.ManyToManyField(related_name='installed_devices', to='general.device'),
        ),
    ]
