# Generated by Django 5.0.1 on 2024-06-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_alter_plugins_target_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugins',
            name='target_devices',
            field=models.ManyToManyField(blank=True, related_name='installed_devices', to='general.device'),
        ),
    ]
