# Generated by Django 5.0.1 on 2024-06-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_alter_plugins_target_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='switches',
            field=models.ManyToManyField(blank=True, related_name='switch_controllers', to='general.device'),
        ),
    ]
