# Generated by Django 5.0.1 on 2025-01-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_alter_controller_switches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='type',
            field=models.CharField(choices=[('onos', 'Onos'), ('odl', 'Open Daylight'), ('faucet', 'Faucet'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='os_type',
            field=models.CharField(choices=[('ubuntu_20_server', 'Ubuntu 20 Server'), ('ubuntu_22_server', 'Ubuntu 22 Server'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
