# Generated by Django 5.0.1 on 2025-01-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_alter_controller_type_alter_device_os_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bridge',
            unique_together={('device', 'name')},
        ),
    ]
