# Generated by Django 5.0.1 on 2025-03-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0023_alter_bridge_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiermodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
