# Generated by Django 5.0.1 on 2025-04-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0024_alter_classifiermodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='api_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
