# Generated by Django 5.0.1 on 2025-04-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0025_port_api_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='api_url',
        ),
        migrations.AddField(
            model_name='bridge',
            name='api_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
