# Generated by Django 5.0.1 on 2025-04-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0026_remove_port_api_url_bridge_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='ovs_port_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
