# Generated by Django 5.0.1 on 2025-05-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0027_port_ovs_port_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='lan_ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('device_type', 'lan_ip_address')},
        ),
    ]
