# Generated by Django 5.0.1 on 2025-05-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0028_alter_device_lan_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridge',
            name='odl_node_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
