# Generated by Django 5.0.1 on 2025-07-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0029_bridge_odl_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='api_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
