# Generated by Django 5.0.1 on 2025-10-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0030_device_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='link_speed',
            field=models.IntegerField(blank=True, help_text='Link speed in Mb/s', null=True),
        ),
    ]
