# Generated by Django 5.0.1 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0031_port_link_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='is_up',
            field=models.BooleanField(blank=True, help_text='Port status: True if up, False if down, None if unknown', null=True),
        ),
    ]

