services:
  monitor:
    container_name: taurine-system-monitor
    restart: unless-stopped
    build: .
    env_file:
      - .env
    environment:
      DEVICE_IP: ${DEVICE_IP}
      API_URL: ${API_URL}
    volumes:
      - .:/app