# Generated by Django 5.0.1 on 2025-02-21 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_data', '0006_alter_flow_dst_mac_alter_flow_src_mac'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('meter', models.PositiveIntegerField()),
                ('duration', models.FloatField()),
                ('packets', models.PositiveIntegerField()),
                ('bytes', models.PositiveIntegerField()),
                ('priority', models.PositiveIntegerField()),
                ('mac_address', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address in format XX:XX:XX:XX:XX:XX.', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')])),
                ('protocol', models.CharField(max_length=10)),
                ('port', models.PositiveIntegerField()),
                ('classification', models.CharField(max_length=50)),
            ],
        ),
    ]
