# Generated by Django 5.0.1 on 2025-05-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_data', '0009_make_flowstat_hypertable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowstat',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='flowstat',
            old_name='duration',
            new_name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='flowstat',
            name='bytes',
        ),
        migrations.RemoveField(
            model_name='flowstat',
            name='meter',
        ),
        migrations.RemoveField(
            model_name='flowstat',
            name='packets',
        ),
        migrations.AddField(
            model_name='flowstat',
            name='byte_count',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowstat',
            name='meter_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flowstat',
            name='packet_count',
            field=models.BigIntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowstat',
            name='classification',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='flowstat',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='flowstat',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowstat',
            name='priority',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flowstat',
            name='protocol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='flowstat',
            index=models.Index(fields=['classification', 'timestamp'], name='network_dat_classif_15edf4_idx'),
        ),
        migrations.AddIndex(
            model_name='flowstat',
            index=models.Index(fields=['timestamp'], name='network_dat_timesta_5634a8_idx'),
        ),
    ]
