# Generated by Django 5.0.1 on 2025-08-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_data', '0013_adjust_compression_for_frequent_queries'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flowstat',
            index=models.Index(fields=['mac_address', 'timestamp'], name='network_dat_mac_add_866198_idx'),
        ),
        migrations.AddIndex(
            model_name='flowstat',
            index=models.Index(fields=['protocol', 'timestamp'], name='network_dat_protoco_6f474f_idx'),
        ),
    ]
