---
- name: Check if ONOS container is already present
  command: docker container inspect onos
  register: docker_inspect
  ignore_errors: true
  changed_when: false

- name: Set container exists variable
  set_fact:
    container_exists: "{{ docker_inspect.rc == 0 }}"

- name: Debug - Show container exists status
  debug:
    msg: "The ONOS container {{ 'exists' if container_exists else 'does not exist' }}."

- name: Pull the latest ONOS Docker image if not exists
  command: docker pull onosproject/onos:2.7-latest
  when: not container_exists

- name: Start the ONOS container if not exists
  command: >
    docker run -d --restart=unless-stopped --name onos -p 8181:8181 -p 8101:8101 -p 5005:5005 -p 830:830 -p 6653:6653
    --network="host" onosproject/onos:2.7-latest
  when: not container_exists


