# Generated by Django 5.0.1 on 2025-10-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_monitoring', '0004_devicestats_compression'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicestats',
            new_name='device_moni_ip_addr_9b306b_idx',
            old_name='device_moni_ip_addr_idx',
        ),
        migrations.RenameIndex(
            model_name='devicestats',
            new_name='device_moni_timesta_3fce1c_idx',
            old_name='device_moni_timesta_idx',
        ),
    ]
