# Generated by Django 5.0.1 on 2025-10-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_monitoring', '0009_portutilizationstats_compression'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portutilizationalert',
            name='unique_port_alert_per_device',
        ),
        migrations.RenameIndex(
            model_name='portutilizationstats',
            new_name='device_moni_ip_addr_5be0ca_idx',
            old_name='port_util_stats_ip_port_time_idx',
        ),
        migrations.RenameIndex(
            model_name='portutilizationstats',
            new_name='device_moni_ip_addr_7778aa_idx',
            old_name='port_util_stats_ip_time_idx',
        ),
        migrations.RenameIndex(
            model_name='portutilizationstats',
            new_name='device_moni_timesta_5a93e0_idx',
            old_name='port_util_stats_time_idx',
        ),
        migrations.AlterUniqueTogether(
            name='portutilizationalert',
            unique_together={('ip_address', 'port_name')},
        ),
    ]
