# Generated by Django 5.0.1 on 2025-10-21 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_monitoring', '0010_remove_portutilizationalert_unique_port_alert_per_device_and_more'),
        ('network_device', '0002_networkdevice_is_ping_target_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_alive', models.BooleanField(default=False, help_text='Device is online if 3+ out of 5 pings succeeded')),
                ('successful_pings', models.IntegerField(help_text='Number of successful pings out of 5')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ping_stats', to='network_device.networkdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='device_moni_device__68353a_idx'), models.Index(fields=['timestamp'], name='device_moni_timesta_d39ebe_idx')],
            },
        ),
    ]
