# Generated by Django 5.0.1 on 2025-10-25 20:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_monitoring', '0013_make_devicepingstats_hypertable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicepingstats',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp of the ping check'),
        ),
    ]
