# Generated by Django 5.0.1 on 2025-10-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_monitoring', '0014_alter_devicepingstats_timestamp'),
        ('network_device', '0002_networkdevice_is_ping_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicepingstats',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp of the ping check'),
        ),
        migrations.AddIndex(
            model_name='devicepingstats',
            index=models.Index(fields=['timestamp', 'is_alive'], name='device_moni_timestamp_is_alive_idx'),
        ),
    ]
