# Generated by Django 5.0.1 on 2025-01-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_monitoring', '0015_alter_devicepingstats_timestamp_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='devicepingstats',
            constraint=models.CheckConstraint(
                name='successful_pings_range_0_5',
                check=models.Q(successful_pings__gte=0, successful_pings__lte=5),
            ),
        ),
    ]
