# Generated by Django 5.0.1 on 2025-10-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_monitoring', '0016_devicepingstats_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='devicepingstats',
            name='successful_pings_range_0_5',
        ),
    ]
