# Generated by Django 5.0.1 on 2025-10-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_monitoring', '0019_add_devicepingstats_constraints'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='devicepingstats',
            name='device_moni_timestamp_is_alive_idx',
        ),
    ]
