---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - autoconf
      - automake
      - libtool
      - git
      - make
      - gcc
      - clang
      - libssl-dev
      - libcap-ng-dev
      - python3
      - python3-pip
    state: present