# Generated by Django 5.0.1 on 2024-02-06 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0006_alter_device_os_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('onos', 'Onos'), ('odl', 'Open Daylight'), ('other', 'Other')], max_length=20)),
                ('lan_ip_address', models.GenericIPAddressField(unique=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller', to='general.device')),
            ],
        ),
    ]
