# Generated by Django 5.0.1 on 2024-02-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
        ('general', '0006_alter_device_os_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='switches',
            field=models.ManyToManyField(related_name='switch_controllers', to='general.device'),
        ),
    ]
