# Generated by Django 5.0.1 on 2024-02-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_controller_switches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Controller',
        ),
    ]
