# Generated by Django 5.1.14 on 2025-11-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network_device', '0004_alter_networkdevice_operating_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNMPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable device name', max_length=100)),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='IP address of the SNMP device')),
                ('vendor', models.CharField(choices=[('mikrotik', 'MikroTik'), ('ubiquiti', 'Ubiquiti'), ('tp_link', 'TP-Link'), ('cisco', 'Cisco'), ('netgear', 'Netgear'), ('d_link', 'D-Link'), ('huawei', 'Huawei'), ('hp', 'HP'), ('other', 'Other')], db_index=True, default='other', help_text='Device vendor/manufacturer', max_length=50)),
                ('community_string', models.CharField(help_text="SNMP community string (typically 'public' or 'private')", max_length=100)),
                ('snmp_version', models.CharField(choices=[('2c', 'SNMP v2c')], default='2c', help_text='SNMP version (v3 support to be added later)', max_length=10)),
                ('port', models.IntegerField(default=161, help_text='SNMP port (default: 161)')),
                ('polling_interval', models.IntegerField(default=60, help_text='Polling interval in seconds (default: 60)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this device should be polled')),
                ('last_successful_poll', models.DateTimeField(blank=True, help_text='Timestamp of last successful SNMP poll', null=True)),
                ('last_poll_attempt', models.DateTimeField(blank=True, help_text='Timestamp of last poll attempt (successful or not)', null=True)),
                ('consecutive_failures', models.IntegerField(default=0, help_text='Number of consecutive polling failures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network_device', models.ForeignKey(blank=True, help_text='Optional link to existing network device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snmp_devices', to='network_device.networkdevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SNMPDeviceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_cpu_alert', models.DateTimeField(blank=True, null=True)),
                ('last_memory_alert', models.DateTimeField(blank=True, null=True)),
                ('last_disk_alert', models.DateTimeField(blank=True, null=True)),
                ('last_interface_alert', models.DateTimeField(blank=True, null=True)),
                ('last_connection_failure_alert', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(help_text='SNMP device for alert tracking', on_delete=django.db.models.deletion.CASCADE, related_name='alert_settings', to='snmp_monitoring.snmpdevice')),
            ],
        ),
        migrations.CreateModel(
            name='SNMPInterfaceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(db_index=True, help_text="Interface name (e.g., 'eth0', 'wlan0')", max_length=100)),
                ('interface_index', models.IntegerField(blank=True, help_text='SNMP interface index (ifIndex)', null=True)),
                ('bytes_in', models.BigIntegerField(default=0, help_text='Total bytes received on interface')),
                ('bytes_out', models.BigIntegerField(default=0, help_text='Total bytes transmitted on interface')),
                ('packets_in', models.BigIntegerField(default=0, help_text='Total packets received on interface')),
                ('packets_out', models.BigIntegerField(default=0, help_text='Total packets transmitted on interface')),
                ('errors_in', models.BigIntegerField(default=0, help_text='Input errors on interface')),
                ('errors_out', models.BigIntegerField(default=0, help_text='Output errors on interface')),
                ('throughput_mbps', models.FloatField(blank=True, help_text='Calculated throughput in Mbps (if available)', null=True)),
                ('utilization_percent', models.FloatField(blank=True, help_text='Interface utilization percentage (if link speed known)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when statistics were collected')),
                ('device', models.ForeignKey(help_text='SNMP device this interface belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='interface_stats', to='snmp_monitoring.snmpdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SNMPMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(blank=True, help_text='CPU usage percentage', null=True)),
                ('memory_usage', models.FloatField(blank=True, help_text='Memory usage percentage', null=True)),
                ('disk_usage', models.FloatField(blank=True, help_text='Disk usage percentage', null=True)),
                ('uptime_seconds', models.BigIntegerField(blank=True, help_text='Device uptime in seconds', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when metric was collected')),
                ('device', models.ForeignKey(help_text='SNMP device this metric belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='snmp_monitoring.snmpdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='snmpdevice',
            index=models.Index(fields=['ip_address'], name='snmp_monito_ip_addr_22fa3f_idx'),
        ),
        migrations.AddIndex(
            model_name='snmpdevice',
            index=models.Index(fields=['vendor'], name='snmp_monito_vendor_070617_idx'),
        ),
        migrations.AddIndex(
            model_name='snmpdevice',
            index=models.Index(fields=['is_active'], name='snmp_monito_is_acti_6fe373_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='snmpdevice',
            unique_together={('ip_address', 'port')},
        ),
        migrations.AddIndex(
            model_name='snmpinterfacestats',
            index=models.Index(fields=['device', 'interface_name', 'timestamp'], name='snmp_monito_device__726f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='snmpinterfacestats',
            index=models.Index(fields=['device', 'timestamp'], name='snmp_monito_device__ff971d_idx'),
        ),
        migrations.AddIndex(
            model_name='snmpinterfacestats',
            index=models.Index(fields=['timestamp'], name='snmp_monito_timesta_30d54f_idx'),
        ),
        migrations.AddIndex(
            model_name='snmpmetrics',
            index=models.Index(fields=['device', 'timestamp'], name='snmp_monito_device__c7e7af_idx'),
        ),
        migrations.AddIndex(
            model_name='snmpmetrics',
            index=models.Index(fields=['timestamp'], name='snmp_monito_timesta_1f76d0_idx'),
        ),
    ]
