# Generated by Django 5.0.1 on 2025-02-13 10:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address in format XX:XX:XX:XX:XX:XX.', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')])),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('switch', 'Switch'), ('access_point', 'Access Point'), ('server', 'Server'), ('controller', 'Controller'), ('vm', 'Virtual Machine'), ('end_user', 'End User')], default='unknown', max_length=20, null=True)),
                ('operating_system', models.CharField(blank=True, choices=[('ubuntu_20_server', 'Ubuntu 20 Server'), ('ubuntu_22_server', 'Ubuntu 22 Server'), ('unknown', 'Unknown'), ('other', 'Other')], default='unknown', max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('number_of_ports', models.IntegerField(blank=True, null=True)),
                ('openvswitch_enabled', models.BooleanField(default=False)),
                ('openvswitch_version', models.CharField(blank=True, max_length=50, null=True)),
                ('openflow_version', models.CharField(blank=True, max_length=50, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_devices', to='account.account')),
            ],
        ),
    ]
