# Generated by Django 5.0.1 on 2025-10-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='is_ping_target',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='device_type',
            field=models.CharField(blank=True, choices=[('switch', 'Switch'), ('access_point', 'Access Point'), ('server', 'Server'), ('controller', 'Controller'), ('vm', 'Virtual Machine'), ('client', 'Client'), ('dns', 'DNS Server'), ('end_user', 'End User')], default='unknown', max_length=20, null=True),
        ),
    ]
