# Generated by Django 5.0.1 on 2025-10-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_device', '0003_make_mac_address_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='operating_system',
            field=models.CharField(blank=True, choices=[('ubuntu_20_server', 'Ubuntu 20 Server'), ('ubuntu_22_server', 'Ubuntu 22 Server'), ('ubuntu_24_server', 'Ubuntu 24 Server'), ('ubuntu_20_desktop', 'Ubuntu 20 Desktop'), ('ubuntu_22_desktop', 'Ubuntu 22 Desktop'), ('ubuntu_24_desktop', 'Ubuntu 24 Desktop'), ('unknown', 'Unknown'), ('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('android', 'Android'), ('ios', 'iOS'), ('chromeos', 'ChromeOS'), ('chromebook', 'Chromebook'), ('other', 'Other')], default='unknown', max_length=20, null=True),
        ),
    ]
