---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  with_items:
    - "/mnt/sniffer"

- name: Copy files to Server
  copy:
    src: "{{ playbook_dir }}/resources/sniffer/"
    dest: "/mnt/sniffer"

- name: Remove existing .env file if it exists
  ansible.builtin.file:
    path: "/mnt/sniffer/.env"
    state: absent

- name: Create .env file with environment variables
  lineinfile:
    path: "/mnt/sniffer/.env"
    line: "{{ item }}"
    create: yes
  loop:
    - "LAN_IP_ADDRESS={{ ip_address }}"
    - "SWITCH_ID={{ switch_id }}"
    - "API_BASE_URL={{ api_base_url }}"
    - "INTERFACE={{ monitor_interface }}"
    - "PORT_TO_CLIENTS={{ port_to_clients }}"
    - "PORT_TO_ROUTER={{ port_to_router }}"
    - "NUM_BYTES={{ num_bytes }}"
    - "NUM_PACKETS={{ num_packets }}"
    - "MODEL_NAME={{ model_name }}"

- name: Build Docker Container
  command: "docker compose -f /mnt/sniffer/docker-compose.yml build --no-cache"

- name: Run Docker Container
  command: "docker compose -f /mnt/sniffer/docker-compose.yml up -d"