# Generated by Django 5.0.1 on 2024-06-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0021_alter_controller_switches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.IntegerField(unique=True)),
                ('meter_type', models.CharField(choices=[('drop', 'drop')], max_length=30)),
                ('rate', models.IntegerField()),
                ('switch_id', models.CharField(max_length=30)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_controller', to='general.device')),
            ],
        ),
    ]
