# Generated by Django 5.0.1 on 2024-06-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='categories',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
