# Generated by Django 5.0.1 on 2024-06-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_alter_controller_switches'),
        ('onos', '0002_meter_categories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meter',
            unique_together={('meter_type', 'rate', 'device')},
        ),
    ]
