# Generated by Django 5.0.1 on 2024-06-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onos', '0003_alter_meter_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meter',
            unique_together={('meter_type', 'rate', 'switch_id')},
        ),
    ]
