# Generated by Django 5.0.1 on 2024-06-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_alter_controller_switches'),
        ('onos', '0004_alter_meter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='general.device'),
        ),
    ]
