# Generated by Django 5.0.1 on 2024-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onos', '0005_alter_meter_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='meter',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='meter',
            name='categories',
        ),
        migrations.AddField(
            model_name='meter',
            name='categories',
            field=models.ManyToManyField(blank=True, to='onos.category'),
        ),
    ]
