# Generated by Django 5.0.1 on 2024-06-13 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_alter_controller_switches'),
        ('onos', '0006_category_alter_meter_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='controller_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OnosOpenFlowDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openflow_id', models.CharField(max_length=30)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openflow_device', to='general.device')),
            ],
        ),
    ]
