# Generated by Django 5.0.1 on 2024-06-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onos', '0007_meter_controller_ip_onosopenflowdevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='device',
            new_name='controller_device',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='controller_ip',
            new_name='switch_ip',
        ),
    ]
