# Generated by Django 5.0.1 on 2024-06-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onos', '0008_rename_device_meter_controller_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='switch_ip',
        ),
    ]
