# Generated by Django 5.0.1 on 2024-06-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onos', '0009_remove_meter_switch_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='meter_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
