# Generated by Django 5.0.1 on 2025-03-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0023_alter_bridge_unique_together'),
        ('onos', '0010_alter_meter_meter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='meter_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='meter',
            unique_together={('controller_device', 'meter_id')},
        ),
    ]
