# Generated by Django 5.0.1 on 2025-03-04 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_device', '0001_initial'),
        ('onos', '0011_alter_meter_meter_id_alter_meter_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='activation_period',
            field=models.CharField(choices=[('weekday', 'Weekday'), ('weekend', 'Weekend'), ('all_week', 'All Week')], default='all_week', max_length=10),
        ),
        migrations.AddField(
            model_name='meter',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='network_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='network_device.networkdevice'),
        ),
        migrations.AddField(
            model_name='meter',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
