# Generated by Django 5.0.1 on 2025-03-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0023_alter_bridge_unique_together'),
        ('network_device', '0001_initial'),
        ('onos', '0012_meter_activation_period_meter_end_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meter',
            unique_together={('controller_device', 'meter_id', 'activation_period', 'start_time', 'end_time', 'network_device')},
        ),
    ]
