# Generated by Django 5.0.1 on 2025-03-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onos', '0013_alter_meter_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meter',
            unique_together={('switch_id', 'meter_id')},
        ),
    ]
