# Generated by Django 5.0.1 on 2025-02-05 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0023_alter_bridge_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=20)),
                ('short_description', models.CharField(max_length=200)),
                ('long_description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('requires_target_device', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PluginInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installed_plugins', to='general.device')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='software_plugin.plugin')),
            ],
            options={
                'unique_together': {('plugin', 'device')},
            },
        ),
        migrations.CreateModel(
            name='PluginRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='software_plugin.plugin')),
                ('required_plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_plugins', to='software_plugin.plugin')),
            ],
            options={
                'unique_together': {('plugin', 'required_plugin')},
            },
        ),
    ]
