# Generated by Django 5.0.1 on 2025-04-21 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnifferInstallationConfig',
            fields=[
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sniffer_config', serialize=False, to='software_plugin.plugininstallation')),
                ('api_base_url', models.URLField(max_length=255)),
                ('monitor_interface', models.CharField(max_length=100)),
                ('port_to_client', models.CharField(max_length=100)),
                ('port_to_router', models.CharField(max_length=100)),
                ('bridge_name', models.CharField(max_length=100)),
            ],
        ),
    ]
