# Generated by Django 5.0.1 on 2025-03-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifier',
            name='telegram_api_key',
            field=models.CharField(max_length=45),
        ),
    ]
