# Generated by Django 5.0.1 on 2025-03-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notifier_telegram_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifier',
            name='telegram_api_key',
            field=models.CharField(max_length=100),
        ),
    ]
