# Generated by Django 5.0.1 on 2025-03-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notifier_telegram_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
