# Generated by Django 5.0.1 on 2025-03-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notifier_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifier',
            name='chat_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
