# Generated by Django 5.0.1 on 2025-03-04 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notifier_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSummaryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(choices=[(1, 'Every hour'), (6, 'Every 6 hours'), (12, 'Every 12 hours'), (24, 'Every 24 hours')])),
                ('top_users_count', models.PositiveIntegerField(default=5, help_text='Number of top users to display')),
                ('top_apps_count', models.PositiveIntegerField(default=5, help_text='Number of top applications to display')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('notifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_summary_notifications', to='notification.notifier')),
            ],
        ),
    ]
