# Generated by Django 5.0.1 on 2025-03-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_networksummarynotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networksummarynotification',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Every minute'), (60, 'Every hour'), (360, 'Every 6 hours'), (720, 'Every 12 hours'), (1440, 'Every 24 hours')]),
        ),
    ]
