# Generated by Django 5.0.1 on 2025-03-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_alter_networksummarynotification_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networksummarynotification',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Every minute'), (10, 'Every 10 minutes'), (60, 'Every hour'), (360, 'Every 6 hours'), (720, 'Every 12 hours'), (1440, 'Every 24 hours')]),
        ),
    ]
