# Generated by Django 5.0.1 on 2025-03-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_alter_networksummarynotification_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUsageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(choices=[(1, 'Every minute'), (10, 'Every 10 minutes'), (60, 'Every hour'), (360, 'Every 6 hours'), (720, 'Every 12 hours'), (1440, 'Every 24 hours')])),
                ('data_limit_mb', models.PositiveIntegerField(help_text='Data limit in MB')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('notifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_usage_notifications', to='notification.notifier')),
            ],
        ),
    ]
