# Generated by Django 5.0.1 on 2025-03-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_applicationusagenotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationusagenotification',
            old_name='celery_task_id',
            new_name='celery_task_name',
        ),
        migrations.RenameField(
            model_name='datausagenotification',
            old_name='celery_task_id',
            new_name='celery_task_name',
        ),
        migrations.RenameField(
            model_name='networksummarynotification',
            old_name='celery_task_id',
            new_name='celery_task_name',
        ),
    ]
