# Generated by Django 5.0.1 on 2025-09-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_rename_celery_task_id_applicationusagenotification_celery_task_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='urgency',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=10),
        ),
    ]
