version: '3.8'

services:
  web:
    container_name: packet-classifier-api
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - GOOGLE_METER_ID=1
      - SOCIAL_MEDIA_METER_ID=3
      - AMAZONAWS_METER_ID=1
      - APPLE_METER_ID=1
      - CLOUDFLARE_METER_ID=1
      - CYBERSEC_METER_ID=1
      - HTTP_METER_ID=1
      - TLS_METER_ID=1
      - DEFAULT_METER_ID=2
      - GOOGLE_METER_PRIORITY=60000
      - SOCIAL_MEDIA_METER_PRIORITY=50000
      - AMAZONAWS_METER_PRIORITY=60000
      - APPLE_METER_PRIORITY=60000
      - CLOUDFLARE_METER_PRIORITY=60000
      - CYBERSEC_METER_PRIORITY=60000
      - HTTP_METER_PRIORITY=60000
      - TLS_METER_PRIORITY=60000
      - DEFAULT_METER_PRIORITY=45000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: 1