# Generated by Django 5.0.1 on 2025-10-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProcessGauges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('rss_mb', models.FloatField()),
                ('heap_mb', models.FloatField()),
                ('gc_gen0', models.IntegerField()),
                ('gc_gen1', models.IntegerField()),
                ('gc_gen2', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('fds', models.IntegerField()),
            ],
            options={
                'db_table': 'telemetry.api_process_gauges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('route', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
                ('bytes', models.BigIntegerField()),
                ('dur_ms', models.FloatField()),
                ('host', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'telemetry.api_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CeleryTaskMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('task', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=32)),
                ('dur_ms', models.FloatField()),
                ('rss_before_mb', models.FloatField(null=True)),
                ('rss_after_mb', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'telemetry.celery_tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('conns', models.IntegerField()),
                ('groups', models.IntegerField()),
                ('msgs_per_s', models.FloatField()),
            ],
            options={
                'db_table': 'telemetry.channels_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbPoolStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('size', models.IntegerField()),
                ('checked_in', models.IntegerField()),
                ('checked_out', models.IntegerField()),
                ('overflow', models.IntegerField()),
            ],
            options={
                'db_table': 'telemetry.db_pool_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GunicornEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('event', models.CharField(max_length=64)),
                ('worker_pid', models.IntegerField()),
            ],
            options={
                'db_table': 'telemetry.gunicorn_events',
                'managed': False,
            },
        ),
    ]
