version: "3"

services:
  sniffer:
    container_name: packet-sniffer
    build: .
    restart: unless-stopped
    cap_add:
      - NET_RAW
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - ./logs:/app/logs

