- name: Create individual network configuration scripts for each interface
  copy:
    dest: "/mnt/config_port_{{ item }}.sh"
    content: |
      #!/bin/bash
      echo "Setting up {{ item }}..."
      sudo ip link set {{ item }} up
    mode: '0755'
  loop: "{{ interfaces }}"

- name: Run each network configuration script initially
  command: "/mnt/config_port_{{ item }}.sh"
  loop: "{{ interfaces }}"

- name: Ensure each configuration script runs at reboot via cron
  cron:
    name: "Configure network interface {{ item }} at reboot"
    special_time: reboot
    job: "/mnt/config_port_{{ item }}.sh"
    user: root
  loop: "{{ interfaces }}"
