---
- name: Install Stats monitor
  hosts: localserver
  gather_facts: yes
  become: true
  vars_files:
    - ../group_vars/all.yml

  roles:
    - ../roles/docker-install-pi
    - ../roles/system-stats
