# Generated by Django 5.0.1 on 2025-05-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_cookie',
            field=models.BigIntegerField(blank=True, editable=False, help_text='Deterministic 64-bit cookie generated from the category name.', null=True, unique=True),
        ),
    ]
