# Generated by Django 5.0.1 on 2025-05-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odl', '0002_category_category_cookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_cookie',
            field=models.CharField(blank=True, editable=False, help_text='Deterministic 64-bit cookie generated from the category name.', max_length=255, null=True, unique=True),
        ),
    ]
