# Generated by Django 5.0.1 on 2025-08-20 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
        ('odl', '0003_alter_category_category_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='model_configuration',
            field=models.ForeignKey(blank=True, help_text='Model configuration this category belongs to (optional for backwards compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odl_categories', to='classifier.modelconfiguration'),
        ),
        migrations.AddField(
            model_name='odlmeter',
            name='model_configuration',
            field=models.ForeignKey(blank=True, help_text='Model configuration this meter is associated with (optional for backwards compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odl_meters', to='classifier.modelconfiguration'),
        ),
    ]
